In [63]:
import pandas as pd
import requests as req
import json

In [64]:
hz_code = 101210101
hz_re_weather = req.get('http://t.weather.sojson.com/api/weather/city/'+str(hz_code))

In [65]:
hz_data = json.loads(hz_re_weather.text)

In [66]:
hz_data['cityInfo']

{'city': '杭州市', 'citykey': '101210101', 'parent': '浙江', 'updateTime': '17:01'}

In [67]:
forecast = hz_data['data']['forecast']

In [71]:
forecast

[{'date': '14',
  'high': '高温 25℃',
  'low': '低温 11℃',
  'ymd': '2023-12-14',
  'week': '星期四',
  'sunrise': '06:47',
  'sunset': '17:00',
  'aqi': 46,
  'fx': '西南风',
  'fl': '1级',
  'type': '晴',
  'notice': '愿你拥有比阳光明媚的心情'},
 {'date': '15',
  'high': '高温 17℃',
  'low': '低温 5℃',
  'ymd': '2023-12-15',
  'week': '星期五',
  'sunrise': '06:48',
  'sunset': '17:00',
  'aqi': 39,
  'fx': '北风',
  'fl': '3级',
  'type': '大雨',
  'notice': '出门最好穿雨衣，勿挡视线'},
 {'date': '16',
  'high': '高温 4℃',
  'low': '低温 1℃',
  'ymd': '2023-12-16',
  'week': '星期六',
  'sunrise': '06:49',
  'sunset': '17:00',
  'aqi': 49,
  'fx': '西北风',
  'fl': '4级',
  'type': '多云',
  'notice': '阴晴之间，谨防紫外线侵扰'},
 {'date': '17',
  'high': '高温 3℃',
  'low': '低温 -1℃',
  'ymd': '2023-12-17',
  'week': '星期日',
  'sunrise': '06:49',
  'sunset': '17:01',
  'aqi': 65,
  'fx': '北风',
  'fl': '3级',
  'type': '多云',
  'notice': '阴晴之间，谨防紫外线侵扰'},
 {'date': '18',
  'high': '高温 3℃',
  'low': '低温 1℃',
  'ymd': '2023-12-18',
  'week': '星期一',
  'sunrise': '

In [72]:
df = pd.DataFrame(forecast)

In [73]:
aqi = df['aqi']

In [74]:
print("var     : {0:.2f}".format(aqi.var()))
print("mean    : {0:.2f}".format(aqi.mean()))
print("std     : {0:.2f}".format(aqi.std()))

var     : 55.98
mean    : 52.13
std     : 7.48


In [75]:
aqi.mean()

52.13333333333333

In [77]:
len(aqi)

15

In [3]:
import numpy as np
import pandas as pd

In [35]:
data = pd.DataFrame(np.zeros((100000,4)),)

In [36]:
def chose_lec(x):
        return pd.Series(np.random.random_integers(1,3,4))

In [37]:
data = data.apply(chose_lec,axis=1)
data.columns=['A','B','C','D']

C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_23520\4219066047.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  return pd.Series(np.random.random_integers(1,3,4))


In [61]:
def anna(x):
    return 3-len(x.value_counts())
result = data.apply(anna,axis=1)

In [70]:
len(data[result>=1])/100000*100

55.935

In [72]:
len(data[result==2])/100000*100

102.114

In [79]:
G1 = np.zeros((7,7))

In [80]:
poss = [[0,1],[0,2],[1,2],
        [2,3],[2,5],[3,4],
        [3,5],[5,6]]
for pos in poss:
    # print(pos)
    G1[pos[0],pos[1]] = 1


In [81]:
G1

array([[0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [82]:
FG1 = G1+G1.T

In [83]:
FG1

array([[0., 1., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [88]:
FG1.dot(FG1).dot(FG1)

array([[2., 3., 5., 2., 1., 2., 1.],
       [3., 2., 5., 2., 1., 2., 1.],
       [5., 5., 4., 6., 1., 6., 1.],
       [2., 2., 6., 2., 3., 5., 1.],
       [1., 1., 1., 3., 0., 1., 1.],
       [2., 2., 6., 5., 1., 2., 3.],
       [1., 1., 1., 1., 1., 3., 0.]])

In [89]:
G1 = np.zeros((6,6))

In [104]:
G1

array([[ 0.,  4.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  8., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  6.],
       [ 0.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [105]:
G1[0,1] = 4
G1[0,2] = 2
G1[1,2] = 1
G1[1,3] = 5
G1[2,3] = 8
G1[2,4] = 10
G1[3,4] = 2
G1[3,5] = 6
G1[4,5] = 3

In [106]:
G1

array([[ 0.,  4.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  8., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  6.],
       [ 0.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [107]:
PG1 = G1+G1.T

In [108]:
PG1

array([[ 0.,  4.,  2.,  0.,  0.,  0.],
       [ 4.,  0.,  1.,  5.,  0.,  0.],
       [ 2.,  1.,  0.,  8., 10.,  0.],
       [ 0.,  5.,  8.,  0.,  2.,  6.],
       [ 0.,  0., 10.,  2.,  0.,  3.],
       [ 0.,  0.,  0.,  6.,  3.,  0.]])

In [109]:
PG1[PG1==0] = np.inf

In [111]:
for i in range(6):
    PG1[i,i] = 0

In [112]:
PG1

array([[ 0.,  4.,  2., inf, inf, inf],
       [ 4.,  0.,  1.,  5., inf, inf],
       [ 2.,  1.,  0.,  8., 10., inf],
       [inf,  5.,  8.,  0.,  2.,  6.],
       [inf, inf, 10.,  2.,  0.,  3.],
       [inf, inf, inf,  6.,  3.,  0.]])

In [115]:
for i in range(6):
    for j in range(6):
        for k in range(6):
            if PG1[j,i]+PG1[i,k]<PG1[j,k]:
                PG1[j,k] = PG1[j,i]+PG1[i,k]

In [116]:
PG1

array([[ 0.,  3.,  2.,  8., 10., 13.],
       [ 3.,  0.,  1.,  5.,  7., 10.],
       [ 2.,  1.,  0.,  6.,  8., 11.],
       [ 8.,  5.,  6.,  0.,  2.,  5.],
       [10.,  7.,  8.,  2.,  0.,  3.],
       [13., 10., 11.,  5.,  3.,  0.]])

In [2]:
import sympy

In [3]:
x = sympy.symbols('x')

In [4]:
exp = 1/(1-4*x)-1-4*x+6*(1/(1-x)-1-x) + 20 + 60*x

In [5]:
G = sympy.symbols('G')

In [6]:
eq = 2*x*(G-20)+3*x**2*G+1/(1-4*x) - 1 -4*x +6/(1-x)-6-6*x - G + 20 + 60*x

In [8]:
results = sympy.solve(eq,G)

In [11]:
results[0].factor()

-2*(20*x**3 + x**2 - 40*x + 10)/((x - 1)*(x + 1)*(3*x - 1)*(4*x - 1))

In [14]:
3**6-(3*2**6-3)

540

In [35]:
import numpy as np

In [82]:
data = np.zeros((5,5))

In [83]:
pos = [(0,0),(0,1),(1,3),(2,4),(3,1)]

In [84]:
for p in pos:
    data[p] = 1

In [85]:
data

array([[1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
# 沃舍尔算法
for i in range(len(data)):
    for j in range(len(data)):
        for k in range(len(data)):
            if j!=i and k!=i:
                data[j,k] = int(data[j,k] or data[i,k]*data[j,i])
print(data)

[[1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [87]:
int(True)

1