In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None

In [5]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [6]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [10]:
string_data.dropna()

1    artichoke
3      avocado
dtype: object

In [8]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [11]:
from numpy import nan as NA

In [12]:
data = pd.Series([1,NA,3.5,NA,7])

In [13]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [16]:
cleaned = data.dropna()

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [19]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data[4] = NA

In [21]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [22]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df = pd.DataFrame(np.random.randn(7,3))

In [24]:
df.iloc[:4,1] = NA

In [25]:
df.iloc[:2,2] = NA

In [26]:
df

0         1         2
0  0.428475       NaN       NaN
1  0.150729       NaN       NaN
2 -1.147467       NaN -0.570088
3 -0.500857       NaN  0.140671
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [27]:
df.dropna()

0         1         2
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [32]:
df.dropna(thresh=2)

0         1         2
2 -1.147467       NaN -0.570088
3 -0.500857       NaN  0.140671
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [43]:
df.dropna(axis=0,subset=[1,2],how='any')

0         1         2
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [44]:
df

0         1         2
0  0.428475       NaN       NaN
1  0.150729       NaN       NaN
2 -1.147467       NaN -0.570088
3 -0.500857       NaN  0.140671
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [45]:
df.fillna(0)

0         1         2
0  0.428475  0.000000  0.000000
1  0.150729  0.000000  0.000000
2 -1.147467  0.000000 -0.570088
3 -0.500857  0.000000  0.140671
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [46]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.428475  0.500000  0.000000
1  0.150729  0.500000  0.000000
2 -1.147467  0.500000 -0.570088
3 -0.500857  0.500000  0.140671
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [47]:
_ = df.fillna(0,inplace=True)

In [48]:
df

0         1         2
0  0.428475  0.000000  0.000000
1  0.150729  0.000000  0.000000
2 -1.147467  0.000000 -0.570088
3 -0.500857  0.000000  0.140671
4 -0.784455  0.432494 -0.154032
5  0.586445  1.443912  0.090122
6 -0.026957  0.112504  0.436853

In [49]:
df = pd.DataFrame(np.random.randn(6,3))

In [50]:
df.iloc[2:,1]

2   -0.692448
3    1.321792
4    0.741677
5   -0.328854
Name: 1, dtype: float64

In [51]:
df

0         1         2
0  0.635030  0.331385 -0.961248
1  0.350662  0.810518 -0.679890
2  0.842283 -0.692448 -2.279276
3 -0.697545  1.321792 -0.299118
4 -0.583357  0.741677 -2.276162
5 -1.264622 -0.328854  0.018829

In [52]:
df.iloc[2:,1] = NA

In [53]:
df

0         1         2
0  0.635030  0.331385 -0.961248
1  0.350662  0.810518 -0.679890
2  0.842283       NaN -2.279276
3 -0.697545       NaN -0.299118
4 -0.583357       NaN -2.276162
5 -1.264622       NaN  0.018829

In [55]:
df.loc[4:,2] = NA

In [56]:
df

0         1         2
0  0.635030  0.331385 -0.961248
1  0.350662  0.810518 -0.679890
2  0.842283       NaN -2.279276
3 -0.697545       NaN -0.299118
4 -0.583357       NaN       NaN
5 -1.264622       NaN       NaN

In [57]:
df.fillna(method='ffill')

0         1         2
0  0.635030  0.331385 -0.961248
1  0.350662  0.810518 -0.679890
2  0.842283  0.810518 -2.279276
3 -0.697545  0.810518 -0.299118
4 -0.583357  0.810518 -0.299118
5 -1.264622  0.810518 -0.299118

In [58]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.635030  0.331385 -0.961248
1  0.350662  0.810518 -0.679890
2  0.842283  0.810518 -2.279276
3 -0.697545  0.810518 -0.299118
4 -0.583357       NaN -0.299118
5 -1.264622       NaN -0.299118

In [59]:
data = pd.Series([1.,NA,3.5,NA,7])

In [60]:
data.fillna(data.mean(),method='')

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [61]:
data = pd.DataFrame({'k1':['one','two']*3+['two'],
                     'k2': [1,1,2,3,3,4,4]})

In [62]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [63]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [65]:
data.drop_duplicates(ignore_index=True)

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [66]:
data['v1'] = range(7)

In [67]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [69]:
data.drop_duplicates(['k1','k2'])

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [70]:
data.drop_duplicates(['k1','k2'],keep='last',)

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [71]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon',
                             'Pastrami','corned beef','Bacon',
                             'pastrami','honey ham','nova lox'],
                     'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [72]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [73]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'corned beef': 'cow',
    'honey ham':'pig',
    'pastrami':'cow',
    'nova lox':'salmon'
}

In [90]:
lowercased = data['food'].map(str.lower)

In [91]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [92]:
data['animal'] = lowercased.map(meat_to_animal)

In [93]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [94]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [95]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [99]:
data['food'].str.lower().map(lambda x:meat_to_animal[x])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [100]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [101]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [102]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [104]:
data.replace([-999,-1000],NA)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [105]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [107]:
newdata = data.replace({-999:NA,-1000:0})

In [108]:
newdata

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [109]:
del newdata

In [139]:
newdata = pd.DataFrame(np.random.randn(3,4))

In [140]:
newdata

0         1         2         3
0 -2.112135 -0.103891 -0.653451  0.504895
1  0.379382 -1.551159 -0.523013  0.638839
2  0.117690  0.201034 -0.454258 -0.596415

In [141]:
newdata.iloc[:2,1] = NA

In [142]:
newdata.iloc[1:,3] = NA

In [143]:
newdata.iloc[2,2] = NA

In [144]:
newdata.replace()

0         1         2         3
0 -2.112135       NaN -0.653451  0.504895
1  0.379382       NaN -0.523013  0.504895
2  0.117690  0.201034 -0.523013  0.504895

In [149]:
newdata.iloc[2,0] = -1

In [150]:
newdata

0         1         2         3
0 -2.112135       NaN -0.653451  0.504895
1  0.379382       NaN -0.523013       NaN
2 -1.000000  0.201034       NaN       NaN

In [151]:
newdata.replace({NA:10,-1:0},)

0          1          2          3
0 -2.112135  10.000000  -0.653451   0.504895
1  0.379382  10.000000  -0.523013  10.000000
2  0.000000   0.201034  10.000000  10.000000

In [152]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                    index=['Ohio','Colorado','New York'],
                    columns=['one','two','three','four'])

In [154]:
transform = lambda x:x[:4].upper()

In [155]:
data.index = data.index.map(transform)

In [156]:
data.index

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [157]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [158]:
data.rename(index=str.title,columns=str.upper,)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [159]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [160]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [161]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [162]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [163]:
data.columns = data.columns.map(str.upper)

In [164]:
data

ONE  TWO  THREE  FOUR
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [165]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [166]:
bins = [18,25,35,60,100]

In [167]:
cats = pd.cut(ages,bins)

In [168]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [169]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [170]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [171]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [172]:
pd.cut(ages,bins,False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [173]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [188]:
pd.cut(ages,bins,labels=group_names,duplicates='drop')

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [175]:
data = np.random.rand(20)

In [176]:
data

array([0.99229475, 0.27471623, 0.07790799, 0.20456676, 0.53521413,
       0.83369481, 0.99641821, 0.20834108, 0.4651394 , 0.69339994,
       0.85375518, 0.87153926, 0.49729591, 0.12913574, 0.97821844,
       0.99861814, 0.59728913, 0.23004923, 0.61881346, 0.03726578])

In [189]:
pd.cut(data,4,precision=2,retbins=True)

([(0.21, 1.79], (-1.37, 0.21], (0.21, 1.79], (0.21, 1.79], (-1.37, 0.21], ..., (0.21, 1.79], (0.21, 1.79], (-1.37, 0.21], (0.21, 1.79], (-1.37, 0.21]]
 Length: 1000
 Categories (4, interval[float64, right]): [(-2.96, -1.37] < (-1.37, 0.21] < (0.21, 1.79] < (1.79, 3.36]],
 array([-2.95665148, -1.3716886 ,  0.20695968,  1.78560796,  3.36425625]))

In [178]:
data.sort()

In [179]:
data

array([0.03726578, 0.07790799, 0.12913574, 0.20456676, 0.20834108,
       0.23004923, 0.27471623, 0.4651394 , 0.49729591, 0.53521413,
       0.59728913, 0.61881346, 0.69339994, 0.83369481, 0.85375518,
       0.87153926, 0.97821844, 0.99229475, 0.99641821, 0.99861814])

In [180]:
data = np.random.randn(1000)

In [181]:
cats = pd.qcut(data,4,)

In [182]:
cats

[(-0.0109, 0.614], (-2.951, -0.706], (-0.0109, 0.614], (-0.0109, 0.614], (-0.706, -0.0109], ..., (0.614, 3.364], (0.614, 3.364], (-2.951, -0.706], (0.614, 3.364], (-0.706, -0.0109]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.951, -0.706] < (-0.706, -0.0109] < (-0.0109, 0.614] < (0.614, 3.364]]

In [183]:
pd.value_counts(cats)

(-2.951, -0.706]     250
(-0.706, -0.0109]    250
(-0.0109, 0.614]     250
(0.614, 3.364]       250
Name: count, dtype: int64

In [184]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(-0.0109, 1.258], (-1.344, -0.0109], (-0.0109, 1.258], (-0.0109, 1.258], (-1.344, -0.0109], ..., (1.258, 3.364], (-0.0109, 1.258], (-1.344, -0.0109], (-0.0109, 1.258], (-1.344, -0.0109]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.951, -1.344] < (-1.344, -0.0109] < (-0.0109, 1.258] < (1.258, 3.364]]

In [186]:
pd.value_counts(pd.qcut(data,[0,0.1,0.5,0.9,1]))

(-1.344, -0.0109]    400
(-0.0109, 1.258]     400
(-2.951, -1.344]     100
(1.258, 3.364]       100
Name: count, dtype: int64

In [190]:
data = pd.DataFrame(np.random.randn(1000,4))

In [191]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.008368    -0.003585     0.004386    -0.047022
std       0.970251     0.970912     1.009624     1.009507
min      -2.637270    -2.923569    -3.158155    -3.217487
25%      -0.690747    -0.684548    -0.733956    -0.737124
50%      -0.008315    -0.023290     0.001996    -0.039694
75%       0.662298     0.679444     0.643899     0.633610
max       2.621358     3.097104     3.417552     3.172399

In [192]:
col = data[2]

In [193]:
col

0      1.252547
1      0.069394
2     -0.837054
3     -0.414269
4      0.628136
         ...   
995   -0.079402
996   -1.470200
997   -0.883826
998    1.408991
999    0.896233
Name: 2, Length: 1000, dtype: float64

In [195]:
col[np.abs(col)>3]

271   -3.158155
276    3.413117
745    3.417552
Name: 2, dtype: float64

In [209]:
data[(np.abs(data)>3).any(axis=1)]

0         1         2         3
160 -1.242467  3.097104  0.609744 -2.014062
271 -1.488105  0.231414 -3.158155  0.260875
276  0.875811 -0.189582  3.413117  0.215820
329 -0.687495  0.023846  0.412539 -3.114477
409 -0.731497  1.147833 -1.742515 -3.217487
640  1.473167  0.459147 -1.013539 -3.121055
745  0.412209 -0.102302  3.417552  0.094061
769 -1.098251  3.064659 -0.692309 -0.448291
836  0.135554 -0.241928  0.721614  3.071007
951  0.436913 -0.069378  0.349716  3.172399

In [210]:
data[np.abs(data)>3] = np.sign(data)*3

In [211]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.008368    -0.003747     0.003714    -0.046813
std       0.970251     0.970404     1.006497     1.007389
min      -2.637270    -2.923569    -3.000000    -3.000000
25%      -0.690747    -0.684548    -0.733956    -0.737124
50%      -0.008315    -0.023290     0.001996    -0.039694
75%       0.662298     0.679444     0.643899     0.633610
max       2.621358     3.000000     3.000000     3.000000

In [212]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0 -1.0
1 -1.0 -1.0  1.0  1.0
2 -1.0 -1.0 -1.0 -1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0 -1.0  1.0 -1.0

In [213]:
df = pd.DataFrame(np.arange(20).reshape(5,4))

In [214]:
sampler = np.random.permutation(5)

In [215]:
sampler

array([0, 4, 1, 2, 3])

In [216]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [224]:
df.take(sampler[sampler<4],axis=1)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [225]:
df = pd.DataFrame(np.arange(20).reshape(5,4))

In [226]:
sampler = np.random.permutation(5)

In [227]:
sampler

array([3, 0, 1, 4, 2])

In [228]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [229]:
df.take(sampler,axis=0,is_copy=)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11

In [230]:
df.iloc[sampler]

0   1   2   3
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11

In [231]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
3  12  13  14  15

In [232]:
choices = pd.Series([5,7,-1,6,4])

In [236]:
draws = choices.sample(n=5,replace=False)

In [237]:
draws

1    7
3    6
4    4
2   -1
0    5
dtype: int64

In [238]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [244]:
newchoices = pd.Series(np.random.permutation(np.arange(5)))

In [245]:
newchoices

0    1
1    2
2    3
3    4
4    0
dtype: int32

In [247]:
newchoices = pd.concat([newchoices,newchoices[:2]])

In [248]:
newchoices

0    1
1    2
2    3
3    4
4    0
0    1
1    2
dtype: int32

In [249]:
df.take(newchoices,)

0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11

In [254]:
df.columns = pd.Index(['Zero','One','Two','Three'])

In [257]:
df.sample(n=30,replace=True,weights='Two',random_state=1,).index.value_counts()

4    10
2     7
3     6
1     4
0     3
Name: count, dtype: int64

In [258]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                   'data1': range(6)})

In [259]:
pd.get_dummies(df.key)

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [267]:
dummies = pd.get_dummies(df.key,prefix='key',dtype=int)

In [268]:
df_with_dummy = df.join(dummies)

In [269]:
df_with_dummy

key  data1  key_a  key_b  key_c
0   b      0      0      1      0
1   b      1      0      1      0
2   a      2      1      0      0
3   c      3      0      0      1
4   a      4      1      0      0
5   b      5      0      1      0

In [270]:
mnames = ['movie_id','title','genres']

In [289]:
movies = pd.read_table('datasets/movies.dat',sep='::',header=None,names=mnames)

C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_3332\3681503823.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table('datasets/movies.dat',sep='::',header=None,names=mnames)


In [290]:
movies.head(10)

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [291]:
all_genres = []

In [292]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [293]:
genres = pd.unique(all_genres)

In [294]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [295]:
zero_matrix = np.zeros((len(movies),len(genres)))

In [296]:
dummies = pd.DataFrame(zero_matrix,columns=genres)

In [297]:
gen = movies.genres[0].split('|')

In [298]:
gen

['Animation', "Children's", 'Comedy']

In [299]:
dummies.columns.get_indexer(gen)

array([0, 1, 2], dtype=int64)

In [300]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1

In [301]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [302]:
movies_windic

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  Genre_Animation  Genre_Children's  \
0      Animation|Children's|Comedy              1.0               1.0   
1     Adventure|Children's|Fantasy              0.0               1.0   
2                   Comedy|Romance              0.0               0.0   
3                     Comedy|Drama              0.0               0.0   
4                           Comedy              0.0               0.0   
...                            ...              ...               ...   
3878                        Comedy              0.0               0.0   
3879                         Drama              0.0               0.0   
3880                         Drama              0.0               0.0   
3881                         Drama              0.0               0.0   
3882                Drama|Thriller              0.0               0.0   

      Genre_Comedy  Genre_Adventure  Genre_Fantasy  Genre_Romance  \
0              1.0              0.0            0.0            0.0   
1              0.0              1.0            1.0            0.0   
2              1.0              0.0            0.0            1.0   
3              1.0              0.0            0.0            0.0   
4              1.0              0.0            0.0            0.0   
...            ...              ...            ...            ...   
3878           1.0              0.0            0.0            0.0   
3879           0.0              0.0            0.0            0.0   
3880           0.0              0.0            0.0            0.0   
3881           0.0              0.0            0.0            0.0   
3882           0.0              0.0            0.0            0.0   

      Genre_Drama  ...  Genre_Crime  Genre_Thriller  Genre_Horror  \
0             0.0  ...          0.0             0.0           0.0   
1             0.0  ...          0.0             0.0           0.0   
2             0.0  ...          0.0             0.0           0.0   
3             1.0  ...          0.0             0.0           0.0   
4             0.0  ...          0.0             0.0           0.0   
...           ...  ...          ...             ...           ...   
3878          0.0  ...          0.0             0.0           0.0   
3879          1.0  ...          0.0             0.0           0.0   
3880          1.0  ...          0.0             0.0           0.0   
3881          1.0  ...          0.0             0.0           0.0   
3882          1.0  ...          0.0             1.0           0.0   

      Genre_Sci-Fi  Genre_Documentary  Genre_War  Genre_Musical  \
0              0.0                0.0        0.0            0.0   
1              0.0                0.0        0.0            0.0   
2              0.0                0.0        0.0            0.0   
3              0.0                0.0        0.0            0.0   
4              0.0                0.0        0.0            0.0   
...            ...                ...        ...            ...   
3878           0.0                0.0        0.0            0.0   
3879           0.0                0.0        0.0            0.0   
3880           0.0                0.0        0.0            0.0   
3881           0.0                0.0        0.0            0.0   
3882           0.0                0.0        0.0            0.0   

      Genre_Myste

In [307]:
movies_windic.iloc[2,3:].sort_values(ascending=False)

Genre_Comedy         1.0
Genre_Romance        1.0
Genre_Animation      0.0
Genre_Horror         0.0
Genre_Film-Noir      0.0
Genre_Mystery        0.0
Genre_Musical        0.0
Genre_War            0.0
Genre_Documentary    0.0
Genre_Sci-Fi         0.0
Genre_Thriller       0.0
Genre_Children's     0.0
Genre_Crime          0.0
Genre_Action         0.0
Genre_Drama          0.0
Genre_Fantasy        0.0
Genre_Adventure      0.0
Genre_Western        0.0
Name: 2, dtype: object

In [309]:
dataf = pd.DataFrame([['green','A'],['red','B'],['blue','A']])

In [311]:
dataf.columns = ['color','class']

In [312]:
dataf

color class
0  green     A
1    red     B
2   blue     A

In [318]:
pd.get_dummies(dataf,dtype=int,prefix={'color':'Color','class':'Class'})

Color_blue  Color_green  Color_red  Class_A  Class_B
0           0            1          0        1        0
1           0            0          1        0        1
2           1            0          0        1        0

In [319]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [324]:
dataf.join(pd.get_dummies(dataf['color'],prefix='color',prefix_sep='.',dtype=int,dummy_na=True))

color class  color.blue  color.green  color.red  color.nan
0  green     A           0            1          0          0
1    red     B           0            0          1          0
2   blue     A           1            0          0          0

In [327]:
dataf.loc['class':0] = np.nan

In [331]:
dataf.iloc[1:0] = NA

In [336]:
pd.get_dummies(data=dataf,dummy_na=NA,dtype=int)

color_blue  color_green  color_nan  class_A  class_B  class_nan
0           0            1          0        1        0          0
1           0            0          1        0        1          0
2           1            0          0        1        0          0

In [335]:
dataf

color class
0  green     A
1    NaN     B
2   blue     A

In [337]:
pd.get_dummies(dataf['class'],drop_first=True)

B
0  False
1   True
2  False

In [339]:
mymatx = np.matrix(np.zeros((5,5)))

In [340]:
mymatx

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [348]:
del mymatx

In [364]:
myarray = np.zeros((5,5))

In [365]:
for i,j in [(1,3),(2,4),(3,1),(3,5),(4,3),(5,1),(5,2),(5,4)]:
    myarray[i-1,j-1] = 1

In [362]:
myarray.dot(myarray)

array([[1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 0., 0., 1., 1.],
       [0., 1., 2., 1., 0.]])

In [366]:
myarray

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.]])

In [370]:
myarray2=myarray.dot(myarray)

In [371]:
myarray3=myarray2.dot(myarray)

In [372]:
myarray4=myarray3.dot(myarray)

In [373]:
myarray5=myarray4.dot(myarray4)

In [375]:
myarray

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.]])

In [378]:
myarray2.dot(myarray)

array([[1., 1., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 2., 1., 1.],
       [1., 1., 1., 1., 0.],
       [2., 0., 1., 0., 2.]])

In [379]:
myarray3.dot(myarray)

array([[1., 0., 2., 1., 1.],
       [1., 1., 1., 1., 0.],
       [3., 1., 2., 1., 2.],
       [1., 0., 2., 1., 1.],
       [3., 2., 2., 2., 1.]])

In [381]:
myarray4.dot(myarray)

array([[3., 1., 2., 1., 2.],
       [1., 0., 2., 1., 1.],
       [4., 2., 4., 3., 2.],
       [3., 1., 2., 1., 2.],
       [3., 1., 5., 3., 2.]])

In [382]:
myarray = np.zeros((4,4))

In [383]:
myones = [[1,2],[2,3],[3,4],[4,1]]

In [385]:
for i,j in myones:
    myarray[i-1,j-1] = 1

In [386]:
myarray

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [387]:
myarray.dot(myarray)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [3]:
import numpy as np
import pandas as pd

In [4]:
np.random.seed(12345)

In [5]:
values = np.random.rand(10)

In [6]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [7]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [9]:
pd.get_dummies(pd.cut(values,bins),dtype=int)

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [10]:
pd.cut(values,bins)

[(0.8, 1.0], (0.2, 0.4], (0.0, 0.2], (0.2, 0.4], (0.4, 0.6], (0.4, 0.6], (0.8, 1.0], (0.6, 0.8], (0.6, 0.8], (0.6, 0.8]]
Categories (5, interval[float64, right]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [12]:
pd.get_dummies(pd.cut(values,bins),dtype=int)

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [13]:
val = 'a,b,   guido'

In [14]:
val.split(',')

['a', 'b', '   guido']

In [18]:
pieces = [x.strip() for x in val.split(',')]

In [19]:
pieces

['a', 'b', 'guido']

In [20]:
first, second, third = pieces

In [21]:
first+ '::' + second + '::' + third

'a::b::guido'

In [22]:
'::'.join(pieces)

'a::b::guido'

In [23]:
'guido' in pieces

True

In [24]:
val.index(',')

1

In [25]:
val.find(':')

-1

In [26]:
val.count(',')

2

In [27]:
val.replace(',','::')

'a::b::   guido'

In [28]:
val.replace(',','')

'ab   guido'

In [30]:
val.count(',',0,1)

0

In [36]:
val.endswith(',',1,4)

True

In [39]:
val.index('0',2)

ValueError: substring not found

In [43]:
val.rfind('  ')

5

In [46]:
val.replace(',','.',2)

'a.b.   guido'

In [48]:
(',-- '+val+',,').strip(',')

'-- a,b,   guido'

In [49]:
val.split(',',1,)

['a', 'b,   guido']

In [50]:
val.casefold()

'a,b,   guido'

In [51]:
val.capitalize()

'A,b,   guido'

In [54]:
''.casefold()

'よるしか'

In [56]:
val.rjust(10)

'a,b,   guido'

In [57]:
import re

In [58]:
text = "foo     bar\t baz   \tqux"

In [59]:
text

'foo     bar\t baz   \tqux'

In [60]:
text.split('\t')

['foo     bar', ' baz   ', 'qux']

In [61]:
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [62]:
regex = re.compile('\s+')

In [63]:
regex.split(text,)

['foo', 'bar', 'baz', 'qux']

In [64]:
regex.findall(text)

['     ', '\t ', '   \t']

In [65]:
text = """
Dave dave@google.com
Steve steve@google.com
Rob rob@google.com
Ryan ryan@google.com
"""

In [135]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+[A-Z]{2,4}'

In [136]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [142]:
regex.findall(text,pos=7,)
regex.finditer()

['ave@google.com', 'steve@google.com', 'rob@google.com', 'ryan@google.com']

In [93]:
m = regex.search(text)

In [94]:
m.group(2)

'@google.com'

In [95]:
str(m)

"<re.Match object; span=(6, 21), match='dave@google.com'>"

In [96]:
print(regex.match(text,))

None


In [148]:
print(re.subn(regex,'REDACTED',text,flags=re.IGNORECASE))

ValueError: cannot process flags argument with a compiled pattern

In [116]:
pattern = r'([A-Z0-9.%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [117]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [124]:
m = regex.match('wesm@bright.net')

In [125]:
m.group(3)

'net'

In [126]:
m.groups()

('wesm', 'bright', 'net')

In [129]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'google', 'com'),
 ('rob', 'google', 'com'),
 ('ryan', 'google', 'com')]

In [130]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3',text))


Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: google, Suffix: com
Rob Username: rob, Domain: google, Suffix: com
Ryan Username: ryan, Domain: google, Suffix: com



In [149]:
data = {'Dave':'dave@google.com','Steve':'steve@gmail.com',
        'Rob':'rob@gmail.com','Wes':np.nan}

In [150]:
data = pd.Series(data)

In [151]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [152]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [153]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [234]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z0-9]{2,4})'

In [166]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z0-9]{2,4})'

In [167]:
data.str.findall(pattern,
                 flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [168]:
matches = data.str.match(pattern,flags=re.IGNORECASE)

In [169]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [184]:
data.str[1] == data.str.get(1)

Dave      True
Steve     True
Rob       True
Wes      False
dtype: bool

In [185]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [186]:
df = pd.DataFrame(np.random.randn(3,4))

In [187]:
df

0         1         2         3
0  1.007189 -1.296221  0.274992  0.228913
1  1.352917  0.886429 -2.001637 -0.371843
2  1.669025 -0.438570 -0.539741  0.476985

In [189]:
df.

'          0         1         2         3\n0  1.007189 -1.296221  0.274992  0.228913\n1  1.352917  0.886429 -2.001637 -0.371843\n2  1.669025 -0.438570 -0.539741  0.476985'

In [201]:
data.str.cat(['@','#','$','%'],na_rep='ERROR',sep='\n',join='inner')

Dave     dave@google.com\n@
Steve    steve@gmail.com\n#
Rob        rob@gmail.com\n$
Wes                ERROR\n%
dtype: object

In [202]:
others = pd.Series(['@','#','$','%'],index=['Rob','Wes','Steve','Dave'])

In [203]:
others

Rob      @
Wes      #
Steve    $
Dave     %
dtype: object

In [209]:
data.str.cat(others,sep='_',join='inner',na_rep='Nan',)

Dave     dave@google.com_%
Steve    steve@gmail.com_$
Rob        rob@gmail.com_@
Wes                  Nan_#
dtype: object

In [215]:
data.str.extract(pat=re.compile(pattern))

0    1    2
Dave   NaN  NaN  NaN
Steve  NaN  NaN  NaN
Rob    NaN  NaN  NaN
Wes    NaN  NaN  NaN

In [213]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [220]:
data.str.extract(pattern,flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [219]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z0-9]{2,4})'

In [223]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [229]:
data.str.startswith(r'[^r]+')

Dave     False
Steve    False
Rob      False
Wes        NaN
dtype: object

In [230]:
pattern = r'[^r]+'

In [233]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [235]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [236]:
data.str.get(1)

Dave       a
Steve      t
Rob        o
Wes      NaN
dtype: object

In [237]:
data.str.isdecimal()

Dave     False
Steve    False
Rob      False
Wes        NaN
dtype: object

In [238]:
newdata = pd.Series(['A12134','234124',u'23123','asfno'],index=['A','B','C','D'])

In [239]:
newdata.str.isdecimal()

A    False
B     True
C     True
D    False
dtype: bool

In [266]:
'四'.isdecimal()

False

In [264]:
'VI'.isdigit()

False

In [267]:
'VI'.isnumeric()

False

In [268]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [276]:
data.str.lower()

Dave     15.0
Steve    15.0
Rob      13.0
Wes       NaN
dtype: float64

In [282]:
data.str.pad(30,'left','-',)

Dave     ---------------dave@google.com
Steve    ---------------steve@gmail.com
Rob      -----------------rob@gmail.com
Wes                                 NaN
dtype: object

In [298]:
data.str.replace(r'@[A-Z]+\.([A-Z])',repl='abc',n=1,case=False,regex=True)

Dave      daveabcom
Steve    steveabcom
Rob        robabcom
Wes             NaN
dtype: object

In [302]:
data.str.slice(0,step=2)

Dave     dv@ogec
Steve    seegalc
Rob       rbgalc
Wes          NaN
dtype: object

In [314]:
data.str.split('[@.]',n=-1,expand=False,regex=True,)

Dave     [dave, google, com]
Steve    [steve, gmail, com]
Rob        [rob, gmail, com]
Wes                      NaN
dtype: object